### ISSUE TITLE
FS error

### ISSUE THREAD

**Issue by xicicora** [iDev0urer/salesforce-angular2-boilerplate#1]
I got error when I tried to run the app:

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\work\Angurlar2 Projects\salesforce-angular2-boilerplate-master.ssh\domain.key'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (C:\work\Angurlar2 Projects\salesforce-angular2-boilerplate-master\app.js:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)

Any idea on how to fix this?

**Comment by watzon** [comment]
Ahh I forgot to include in the instructions that you need to generate a keypair to run a local server over SSH. I'll update the documentation.

**Comment by watzon** [comment]
@xicicora the README has been updated so I am going to close this. Please reopen if you continue to have issues.
